name: 'lending_club'
version: '1.0.0'
config-version: 2

profile: 'lending_club'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lending_club:
    staging:
      +materialized: table
